{
 "title": "Alertes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Etat détecteur de fumée", "type": "alertlist", "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Etat détecteur fumée couloir",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:SmokeCouloir",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Etat détecteur  fumée palier",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:SmokePalier",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "T° ext : données depuis 24H ?",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Température",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Extérieur\"",
     "timeField": "date"
    }
   ]
  },
  { "title": "Alertes météo", "type": "alertlist", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 } },
  {
   "title": "Alerte Vigilance Météo",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "risk",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:vigilanceMeteo",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Alerte Vigilance inondation",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "inondation",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:vigilanceMeteo",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "T° SDB: données depuis 24H ?",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Température",
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Etage\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Vigilance gelée",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source=\"T-Extérieur\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Vigilance chaleur véranda",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source=\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Vigilance qualité de l'air",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "qualite-air",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:air",
     "timeField": "date"
    }
   ]
  },
  { "title": "Alertes absence données", "type": "alertlist", "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 } },
  {
   "title": "Batterie fumée couloir",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:SmokeCouloir",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie fumée palier",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:SmokePalier",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie détecteur de fumée couloir",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:SmokeCouloir",
     "timeField": "date"
    }
   ]
  },
  { "title": "Alertes batteries", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 } },
  { "type": "singlestat", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 }, "format": "none", "valueName": "last_time" },
  { "type": "singlestat", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 }, "format": "none", "valueName": "last_time" },
  {
   "title": "Batterie détecteur de fumée palier",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:SmokePalier",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie porte  cuisine baie sud",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:CuisineBaieSud",
     "timeField": "date"
    }
   ]
  }
 ]
}