{
 "title": "Batteries",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Batterie  sonde fumée couloir",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:SmokeCouloir",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie porte cuisine baie sud",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:CuisineBaieSud",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie sonde vibration véranda",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:VerandaVibration",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie sonde fumée palier",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:SmokePalier",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie sonde présence cuisine",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:CuisinePresence",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie porte véranda baie sud",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:VerandaBaieSud",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie sonde présence salon",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:SalonPresence",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie porte véranda baie est",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:\"VerandaBaieEst\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Batterie sonde présence véranda",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "battery",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:VerandaPresence",
     "timeField": "date"
    }
   ]
  },
  { "type": "singlestat", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 }, "format": "none", "valueName": "last_time" },
  { "type": "singlestat", "gridPos": { "h": 3, "w": 5, "x": 6, "y": 16 }, "format": "none", "valueName": "last_time" }
 ]
}