{
 "title": "DS-températures",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "Source",
    "query": "{\"find\": \"fields\", \"source\": \"@source\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Véranda T°",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "content": "<style type=\"text/css\">\np.markdown-html.panel-text-content {\noverflow: hidden;\n}\np.markdown-html.panel-text-content iframe {\nheight:225px;\n}\n</style>\n<script type=\"text/javascript\">\nvar weatherProperties = 'lat=49.2114440999999&lon=-0.4065946000000622&color=#00aaff&text-color=#FFFFFF&units=si&lang=fr';\n\n// initial load\ndocument.getElementById('embedweather').src = 'http://forecast.io/embed/?ts=' + (Date.now()) + '#' + weatherProperties;\n\n// refresh\nvar weatherRefresh = setInterval(function() { document.getElementById('embedweather').src = 'http://forecast.io/embed/?ts=' + (Date.now()) + '#' + weatherProperties; }, 1800000);\n\n</script>\n<iframe id=\"embedweather\" height=\"100%\" src=\"#\" style=\"margin: 0; padding: 0; border: none; width:100%; position:relative; top:-50px; overflow:hidden; margin-bottom: -70px;\"></iframe>\n"
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 } },
  {
   "title": "Véranda T° Min",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "format": "celsius",
   "valueName": "min",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source=\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Véranda T° Max",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "format": "celsius",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "content": "<script>\n  var callbackFunction = function(data) {\n    \n    //import time\n    //T = time.strptime(\"05:42PM\", \"%I:%M%p\")\n    //hour, minutes = T.tm_hour, T.tm_min\n    //print(\"{0}:{1}\".format(hour, minutes))\n\n    var wind = data.query.results.channel.wind;    \n    //alert(wind.chill);\n    $(\"#myWindspeed\").text(wind.speed) ;\n\n   var astronomy = data.query.results.channel.astronomy;\n    $(\"#mySunrise\").text(astronomy.sunrise) ;\n\n    $(\"#mySunset\").text(astronomy.sunset) ;\n\n   var condition = data.query.results.channel.item.condition; \n   $(\"#myTemperature\").text(condition.temp) ;\n  };\n</script>\n<script src=\"https://query.yahooapis.com/v1/public/yql?q=select item, condition, wind, astronomy from weather.forecast where woeid = 623598 and u='c'&format=json&callback=callbackFunction\"></script>\n\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\n\n<style type=\"text/css\">\n\n#MonStyle{\n\nbackground: purple;\ntext-align: center;\nmargin-top: 0px;\nfont: bold 22px arial, sans-serif;\n width: 100%;\n padding: 2px; \n border-spacing: 2px; \n}\n\n.tabcenter{\n   margin-left:auto;\n   margin-right:auto;\n}\n\n</style>\n</head>\n<body>\n<div id=\"MonStyle\">Météo\n\n<table id=\"MaTable\" class=\"tabcenter\">\n  <tr>\n    <td>Temperature : </td><td><span id=\"myTemperature\" /> &deg;C</td>\n  </tr>\n  <tr>\n    <td>Lever du soleil : </td><td><span id=\"mySunrise\" /></td>\n  </tr>\n  <tr>\n   <td>Coucher du soleil : </td> <td><span id=\"mySunset\" /></td>\n  </tr>\n    <td>Vent :  </td> <td> <span id=\"myWindspeed\" /> km/h</td>\n  </tr>\n</table>\n</div>\n</body>\n</html>"
  },
  {
   "title": "Quailté de l'air",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "qualite-air",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:air",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 12 },
   "content": "<script>\n  var callbackFunction = function(data) {\n    var ville = data.ville ;\n    $(\"#myVille\").text(ville) ;\n\n    var qualite-air = data.qualite-air ;\n    $(\"#myQair\").text(qualite-air) ;\n    \n  };\n</script>\n\n<script>\n\n</script>\n    \n<script src=\"http://192.168.1.34/qair/qair.json&callback=callbackFunction\">;\nconsole.log(src);\n</script>\n\nVille:  <span id=\"myVille\" /></br>\nQualité air: <span id=\"myQair\" /></br>\n"
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 12 },
   "content": "<script>\nvar fileName = \"http://192.168.1.34/uv/uv.txt\";\n\n\tvar txtFile;\n    if (window.XMLHttpRequest)\n        {// code for IE7+, Firefox, Chrome, Opera, Safari\n        txtFile = new XMLHttpRequest();\n    }\n\telse\n    {// code for IE6, IE5\n        txtFile = new ActiveXObject(\"Microsoft.XMLHTTP\");\n    }\n\ttxtFile.open(\"GET\",fileName,false);\n\ttxtFile.send();\n\tvar txtDoc=txtFile.responseText;\n\tvar lines = txtDoc.split(\"\\r\\n\"); // values in lines[0], lines[1]...\n  write(11);\n\t//write(lines[0]);\n\t//write(lines[1]);\n\n</script>\n    \nUV:  <lines[0]></br>\n\n"
  },
  {
   "title": "Présence maison",
   "type": "heatmap",
   "description": "0 : Absent\n1 : Présent",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "maison",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "source:\"presence\"",
     "timeField": "date"
    }
   ]
  },
  { "title": "Extérieur", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Extérieur T°",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "query": "source:\"T-Extérieur\""
         }
        ]
       },
       "type": "filters"
      },
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Extérieur Humidité",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Humidity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Extérieur\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Extérieur T° max",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Extérieur\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Extérieur T° min",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:\"T-Extérieur\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Extérieur - Température",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Extérieur\"",
     "timeField": "date"
    }
   ]
  },
  { "title": "Salon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Salon T°",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Salon\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Humidity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Salon\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Salon T° min",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source:\"T-Salon\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Salon T° max",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Salon\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Salon - Température",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Salon\"",
     "timeField": "date"
    }
   ]
  },
  { "title": "Véranda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Véranda T°",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "query": "source:\"T-Veranda\""
         }
        ]
       },
       "type": "filters"
      },
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Humidity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "T° min",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 34 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source=\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "T° max",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "query": "source:\"T-Veranda\""
         }
        ]
       },
       "type": "filters"
      },
      { "field": "date", "id": "2", "settings": { "interval": "2d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Véranda -  Température",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:\"T-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Billard T°",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Billard\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 40 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Humidity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:T-Billard",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Billard T° min",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 40 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "source=\"T-Billard\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Billard T° max",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 40 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:T-Billard",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Billard - Température",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:T-Billard",
     "timeField": "date"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Consommation électrique",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "content": "<iframe width=\"500\" height=\"400\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"src=\"http://192.168.1.34/linky/linky_days.png\"></iframe>"
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } }
 ]
}