{
 "title": "Etage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chambre parents T°",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-ChambreParents\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Chambre Anaïs T°",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-ChambreAnais\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Chambre sarah T°",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-ChambreSarah\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Salle de bain T°",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Temperature",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Etage\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Humidité chambre parents",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Humidity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-ChambreParents\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Humidité chambre Anaïs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Humidity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-ChambreAnais\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Humidité chambre Sarah",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Humidity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-ChambreSarah\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Humidité Salle de bain",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "My-Humidity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"T-Etage\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Détecteur fumée palier",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source:Smoke-Palier",
     "timeField": "date"
    }
   ]
  },
  { "type": "singlestat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 }, "format": "none", "valueName": "last_time" }
 ]
}