{
 "title": "Rez-de-chaussée",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Luminosité salon",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lux",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"Lux-Salon\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Luminosité  cuisine",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lux",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"Lux-Cuisine\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Luminosité véranda",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "lux",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "source=\"Lux-Veranda\"",
     "timeField": "date"
    }
   ]
  },
  { "type": "singlestat", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 }, "format": "none", "valueName": "last_time" }
 ]
}